# {{ ansible_managed }}
server {
    listen 80;
    server_name {{ ansilume_nginx_server_name }};
    root /var/www/web;
    index index.php;

    charset utf-8;
    client_max_body_size {{ ansilume_nginx_client_max_body_size }};

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout {{ ansilume_nginx_fastcgi_timeout }};
    }

    location ~ /\.(ht|git) {
        deny all;
    }
}
