; {{ ansible_managed }}
upload_max_filesize = {{ ansilume_php_upload_max_filesize }}
post_max_size = {{ ansilume_php_post_max_size }}
max_execution_time = {{ ansilume_php_max_execution_time }}
memory_limit = {{ ansilume_php_memory_limit }}
date.timezone = {{ ansilume_php_timezone }}
display_errors = Off
log_errors = On
error_log = /var/log/php_errors.log
