---
- name: Restart ansilume stack
  community.docker.docker_compose_v2:
    project_src: "{{ ansilume_install_dir }}"
    project_name: "{{ ansilume_compose_project }}"
    state: present
    pull: always
    build: always
    recreate: always
  become: true
  become_user: "{{ ansilume_system_user }}"

- name: Reload nginx
  community.docker.docker_container_exec:
    container: "{{ ansilume_compose_project }}_nginx"
    command: nginx -s reload
  become: true
  become_user: "{{ ansilume_system_user }}"
