---
- name: Template .env file
  ansible.builtin.template:
    src: env
    dest: "{{ ansilume_install_dir }}/.env"
    owner: "{{ ansilume_system_user }}"
    group: "{{ ansilume_system_group }}"
    mode: "0600"
  become: true
  notify: Restart ansilume stack

- name: Template docker-compose.yaml
  ansible.builtin.template:
    src: docker-compose.yaml
    dest: "{{ ansilume_install_dir }}/docker-compose.yaml"
    owner: "{{ ansilume_system_user }}"
    group: "{{ ansilume_system_group }}"
    mode: "0640"
  become: true
  notify: Restart ansilume stack

- name: Template nginx configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: "{{ ansilume_install_dir }}/docker/nginx/default.conf"
    owner: "{{ ansilume_system_user }}"
    group: "{{ ansilume_system_group }}"
    mode: "0640"
  become: true
  notify: Reload nginx

- name: Template PHP configuration
  ansible.builtin.template:
    src: php.ini
    dest: "{{ ansilume_install_dir }}/docker/php/php.ini"
    owner: "{{ ansilume_system_user }}"
    group: "{{ ansilume_system_group }}"
    mode: "0640"
  become: true
  notify: Restart ansilume stack

- name: Template MariaDB configuration
  ansible.builtin.template:
    src: my.cnf
    dest: "{{ ansilume_install_dir }}/docker/mysql/my.cnf"
    owner: "{{ ansilume_system_user }}"
    group: "{{ ansilume_system_group }}"
    mode: "0640"
  become: true
  when: ansilume_db_local
  notify: Restart ansilume stack
